import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./footer";
import { Toaster } from "@/components/ui/toaster";
import i18nConfig from "@/i18nConfig";
import TranslationProvider from "./(components)/TranslationProvider";
import initTranslations from "../i18n";
import dynamic from "next/dynamic";

const i18nNamespaces = ["common"];
const inter = Inter({ subsets: ["latin"] });

const Header = dynamic(() => import("./header"), { ssr: false });

export const metadata: Metadata = {
  title: "Rush B",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default async function RootLayout({
  children,
  params,
}: Readonly<RootLayoutProps>) {
  const { t, resources } = await initTranslations(
    params.locale,
    i18nNamespaces
  );

  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          <TranslationProvider
            resources={resources}
            locale={params.locale}
            namespaces={i18nNamespaces}
          >
            <Header />
            <main className="flex-1">{children}</main>
            <Toaster />
            <Footer />
          </TranslationProvider>
        </div>
      </body>
    </html>
  );
}
