import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";
import { Toaster } from "@/components/ui/toaster";
import i18nConfig from '@/i18nConfig';
import TranslationProvider from "./(components)/TranslationProvider"
import initTranslations from "../i18n";


const i18nNamespaces = ['common'];
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rush B",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default async function RootLayout({
  children,
  params
}: Readonly<RootLayoutProps>) {
  const { t, resources } = await initTranslations(params.locale, i18nNamespaces);

  return (
    <html lang={params.locale}>
        <body className={inter.className}>
        <TranslationProvider resources={resources} locale={params.locale} namespaces={i18nNamespaces}>
          <Header />
          <main>{children}</main>
          <Toaster />
          <Footer />
        </TranslationProvider>
        </body>
      </html>

  );
}
